local_backend: true

backend:
  name: git-gateway
  branch: main  # or master

media_folder: ""
public_folder: ""

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    path: "{{slug}}/index"
    format: toml-frontmatter
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }

